/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package osaifu.management.bot;

import org.junit.Test;

public class EchoApplicationTest {
    @Test public void testSomeLibraryMethod() {

    }
}
